=== NoelMirandaDev/csd-430/module-9/Assignment-1/PLPSS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://www.mockpolicewebsite.com/PLPSS"
		   xmlns="http://www.mockpolicewebsite.com/PLPSS"
		   elementFormDefault="qualified">
 <!--
    xmlns:xs="http://www.w3.org/2001/XMLSchema" :
    - This declares the XML Schema namespace (xs), which is required to use XML Schema-related elements like xs:schema, 
    xs:element, xs:complexType, etc.

    targetNamespace="http://www.mockpolicewebsite.com/PLPSS" :
    - Specifies the target namespace for this schema. It ensures that elements defined in this schema belong to the 
    "http://www.mockpolicewebsite.com/PLPSS" namespace.

    xmlns="http://www.mockpolicewebsite.com/PLPSS" :
    - This sets the default namespace for the schema. It means that all elements defined in this schema will be associated 
    with the "http://www.mockpolicewebsite.com/PLPSS" namespace, unless otherwise specified.

    elementFormDefault="qualified" :
    - Specifies that all elements in this schema must be *qualified* with the target namespace in the XML document.
    - In other words, the XML elements must explicitly include the namespace (e.g., <licensePlate>) to be valid according to this schema.
-->

	<!-- Root Element -->
	<xs:element name="licensePlate">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="owner" type="OwnerType"/>
			</xs:sequence>
			<xs:attribute name="number" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<!-- Owner Info -->
	<xs:complexType name="OwnerType">
		<xs:sequence>
			<xs:element name="ownerName" type="OwnerNameType"/>
			<xs:element name="address" type="AddressType"/>
			<xs:element name="vehicle" type="VehicleType"/>
			<xs:element name="criminalRecords" type="CriminalRecordsType"/>
		</xs:sequence>
		<xs:attribute name="activeWarrant" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="yes"/>
					<xs:enumeration value="no"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<!-- Owner Name -->
	<xs:complexType name="OwnerNameType">
		<xs:sequence>
			<xs:element name="first" type="xs:string"/>
			<xs:element name="last" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Address -->
	<xs:complexType name="AddressType">
		<xs:sequence>
			<xs:element name="street" type="xs:string"/>
			<xs:element name="unitIdentifier" type="xs:string" minOccurs="0"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zipcode" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Vehicle info -->
	<xs:complexType name="VehicleType">
		<xs:sequence>
			<xs:element name="make" type="xs:string"/>
			<xs:element name="model" type="ModelType"/>
			<xs:element name="color" type="ColorType"/>
		</xs:sequence>
		<xs:attribute name="vin" type="xs:string" use="required"/>
		<xs:attribute name="status" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="stolen"/>
					<xs:enumeration value="clean"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<!-- Vehicle Model info -->
	<xs:complexType name="ModelType">
		<xs:sequence>
			<xs:element name="modelName" type="xs:string"/>
			<xs:element name="year" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Vehicle Color info -->
	<xs:complexType name="ColorType">
		<xs:sequence>
			<xs:element name="colorName" type="xs:string"/>
			<xs:element name="code" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Criminal Records -->
	<xs:complexType name="CriminalRecordsType">
		<xs:sequence>
			<xs:element name="record" type="RecordType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Record info -->
	<xs:complexType name="RecordType">
		<xs:sequence>
			<xs:element name="offense" type="xs:string"/>
			<xs:element name="date" type="xs:date"/>
			<xs:element name="location" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== NoelMirandaDev/csd-430/module-9/Assignment-1/PoliceLicencePlateSearchSystem2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style4PLPSS.css"?>
<licensePlate number="2Fast2Furious"
			  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xmlns="http://www.mockpolicewebsite.com/PLPSS"
			  xsi:schemaLocation="http://www.mockpolicewebsite.com/PLPSS PLPSS.xsd">	  
<!--
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" :
    - This declares the XML Schema Instance namespace (xsi), which is needed to use attributes like xsi:schemaLocation 
    in the XML document.
    
    xmlns="http://www.mockpolicewebsite.com/PLPSS" :
    - This associates the XML document with the "http://www.mockpolicewebsite.com/PLPSS" namespace.
    - This ensures the elements in this XML are validated according to the schema that has the same namespace.

    xsi:schemaLocation="http://www.mockpolicewebsite.com/PLPSS PLPSS.xsd" :
    - This attribute tells the XML parser where to find the XML Schema document for validation.
    - The first part (`http://www.mockpolicewebsite.com/PLPSS`) is the target namespace for the schema.
    - The second part (`PLPSS.xsd`) is the location of the XSD file that defines the validation rules for this XML document.
    -->
	<owner activeWarrant="yes">
		<ownerName>
			<first>John</first>
			<last>Doe</last>
		</ownerName>
		
		<address>
			<street>0000 N Somewhere</street>
			<unitIdentifier>Apt. 2</unitIdentifier>
			<city>Chicago</city>
			<state>Illinois</state>
			<zipcode>60634</zipcode>
		</address>
	
		<vehicle vin="1HGCM82633A004352" status="stolen">
			<make>Toyota</make>
			<model>
				<modelName>Corolla</modelName>
				<year>2006</year>
			</model>
			<color>
				<colorName>Blue</colorName>
				<code>#0000FF</code>
			</color>
		</vehicle>
		
		<criminalRecords>
			<record>
				<offense>Speeding</offense>
				<date>2023-06-15</date>
				<location>Springfield</location>
			</record>
			
			<record>
				<offense>Grand Theft Auto</offense>
				<date>2022-11-03</date>
				<location>Chicago</location>
			</record>
		</criminalRecords>
	</owner>
</licensePlate>
