=== NoelMirandaDev/csd-430/module-9/Assignment-1/PLPSS.dtd
<!ELEMENT licensePlate (owner)>
<!ATTLIST licensePlate number CDATA #REQUIRED>

<!ELEMENT owner (ownerName, address, vehicle, criminalRecords)>
<!ATTLIST owner 
	activeWarrant CDATA #REQUIRED>

<!ELEMENT ownerName (first, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>

<!ELEMENT address (street, unitIdentifier, city, state, zipcode)>
	<!ELEMENT street (#PCDATA)>
	<!ELEMENT unitIdentifier (#PCDATA)>
	<!ELEMENT city (#PCDATA)>
	<!ELEMENT state (#PCDATA)>
	<!ELEMENT zipcode (#PCDATA)>

<!ELEMENT vehicle (make, model, color)>
<!ATTLIST vehicle 
	vin CDATA #REQUIRED
	status CDATA #REQUIRED>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (modelName, year)>
	<!ELEMENT modelName (#PCDATA)>
	<!ELEMENT year (#PCDATA)>
<!ELEMENT color (colorName, code)>
	<!ELEMENT colorName (#PCDATA)>
	<!ELEMENT code (#PCDATA)>
	
<!ELEMENT criminalRecords (record*)>
<!ELEMENT record (offense, date, location)>
	<!ELEMENT offense (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT location (#PCDATA)>

=== NoelMirandaDev/csd-430/module-9/Assignment-1/PoliceLicencePlateSearchSystem1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE licensePlate SYSTEM "PLPSS.dtd">
<?xml-stylesheet type="text/css" href="style4PLPSS.css"?>
<licensePlate number="2Fast2Furious">
	<owner activeWarrant="Yes">
		<ownerName>
			<first>John</first>
			<last>Doe</last>
		</ownerName>
		
		<address>
			<street>0000 N Somewhere</street>
			<unitIdentifier>Apt. 2</unitIdentifier>
			<city>Chicago</city>
			<state>Illinois</state>
			<zipcode>60634</zipcode>
		</address>
	
		<vehicle vin="1HGCM82633A004352" status="stolen">
			<make>Toyota</make>
			<model>
				<modelName>Corolla</modelName>
				<year>2006</year>
			</model>
			<color>
				<colorName>Blue</colorName>
				<code>#0000FF</code>
			</color>
		</vehicle>
		
		<criminalRecords>
			<record>
				<offense>Speeding</offense>
				<date>2023-06-15</date>
				<location>Springfield</location>
			</record>
			
			<record>
				<offense>Grand Theft Auto</offense>
				<date>2022-11-03</date>
				<location>Chicago</location>
			</record>
		</criminalRecords>
	</owner>
</licensePlate>
